### ISSUE TITLE
Invalid value when importing/editing positions from executable

### ISSUE THREAD

**Issue by Muzzarino** [igorseabra4/HeroesPowerPlant#27]
On versions later than v0.87 where the functionality to read things from the executable was implemented, an error pops up an invalid value error which should be returning the actual positions from the exe.

Error log:
```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentOutOfRangeException: Value of '-180' is not valid for 'Value'. 'Value' should be between 'Minimum' and 'Maximum'. (Parameter 'value')
Actual value was -180.
   at System.Windows.Forms.NumericUpDown.set_Value(Decimal value)
   at HeroesPowerPlant.ConfigEditor.ConfigEditor.ComboBoxTeam_SelectedIndexChanged(Object sender, EventArgs e)
   at System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ComboBox.WmReflectCommand(Message& m)
   at System.Windows.Forms.ComboBox.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
System.Private.CoreLib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.700.19.47502
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.0.1/System.Private.CoreLib.dll
----------------------------------------
HeroesPowerPlant
    Assembly Version: 1.6.0.0
    Win32 Version: 1.6.0.0
    CodeBase: file:///C:/tools/HeroesPowerPlant_v0.8.9/HeroesPowerPlant.dll
----------------------------------------
System.Runtime
    Assembly Version: 4.2.1.0
    Win32 Version: 4.700.19.51008
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.0.1/System.Runtime.dll
----------------------------------------
SharpDX
    Assembly Version: 4.2.0.0
    Win32 Version: 4.2.0
    CodeBase: file:///C:/tools/HeroesPowerPlant_v0.8.9/SharpDX.dll
----------------------------------------
System.Threading.Thread
    Assembly Version: 4.1.1.0
    Win32 Version: 4.700.19.51008
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.0.1/System.Threading.Thread.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.800.19.48001
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/3.0.1/System.Windows.Forms.dll
----------------------------------------
SharpDX.Direct3D11
    Assembly Version: 4.2.0.0
    Win32 Version: 4.2.0
    CodeBase: file:///C:/tools/HeroesPowerPlant_v0.8.9/SharpDX.Direct3D11.dll
----------------------------------------
System.ComponentModel.Primitives
    Assembly Version: 4.2.1.0
    Win32 Version: 4.700.19.51008
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.0.1/System.ComponentModel.Primitives.dll
----------------------------------------
System.Drawing.Primitives
    Assembly Version: 4.2.0.0
    Win32 Version: 4.700.19.51008
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.0.1/System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    Assembly Version: 4.1.1.0
    Win32 Version: 4.700.19.51008
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.0.1/System.Collections.Specialized.dll
----------------------------------------
System.Runtime.InteropServices
    Assembly Version: 4.2.1.0
    Win32 Version: 4.700.19.51008
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.0.1/System.Runtime.InteropServices.dll
----------------------------------------
System.Threading
    Assembly Version: 4.1.1.0
    Win32 Version: 4.700.19.51008
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.0.1/System.Threading.dll
----------------------------------------
System.Collections
    Assembly Version: 4.1.1.0
    Win32 Version: 4.700.19.51008
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.0.1/System.Collections.dll
----------------------------------------
System.Diagnostics.TraceSource
    Assembly Version: 4.1.1.0
    Win32 Version: 4.700.19.51008
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.0.1/System.Diagnostics.TraceSource.dll
----------------------------------------
System.Runtime.Extensions
    Assembly Version: 4.2.1.0
    Win32 Version: 4.700.19.51008
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.0.1/System.Runtime.Extensions.dll
----------------------------------------
System.Diagnostics.Debug
    Assembly Version: 4.1.1.0
    Win32 Version: 4.700.19.51008
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.0.1/System.Diagnostics.Debug.dll
----------------------------------------
SharpDX.DXGI
    Assembly Version: 4.2.0.0
    Win32 Version: 4.2.0
    CodeBase: file:///C:/tools/HeroesPowerPlant_v0.8.9/SharpDX.DXGI.dll
----------------------------------------
SharpDX.Mathematics
    Assembly Version: 4.2.0.0
    Win32 Version: 4.2.0
    CodeBase: file:///C:/tools/HeroesPowerPlant_v0.8.9/SharpDX.Mathematics.dll
----------------------------------------
System.Drawing.Common
    Assembly Version: 4.0.1.0
    Win32 Version: 4.700.19.46214
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/3.0.1/System.Drawing.Common.dll
----------------------------------------
Heroes.SDK
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/tools/HeroesPowerPlant_v0.8.9/Heroes.SDK.dll
----------------------------------------
Microsoft.Win32.Primitives
    Assembly Version: 4.1.1.0
    Win32 Version: 4.700.19.51008
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.0.1/Microsoft.Win32.Primitives.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    Assembly Version: 4.1.1.0
    Win32 Version: 4.700.19.51008
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.0.1/System.ComponentModel.EventBasedAsync.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.800.19.48001
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/3.0.1/Accessibility.dll
----------------------------------------
System.ComponentModel.TypeConverter
    Assembly Version: 4.2.1.0
    Win32 Version: 4.700.19.51008
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.0.1/System.ComponentModel.TypeConverter.dll
----------------------------------------
System.Resources.ResourceManager
    Assembly Version: 4.1.1.0
    Win32 Version: 4.700.19.51008
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.0.1/System.Resources.ResourceManager.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    Assembly Version: 4.0.1.0
    Win32 Version: 4.700.19.46214
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/3.0.1/Microsoft.Win32.SystemEvents.dll
----------------------------------------
System.Collections.Concurrent
    Assembly Version: 4.0.14.0
    Win32 Version: 4.700.19.51008
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.0.1/System.Collections.Concurrent.dll
----------------------------------------
System.ComponentModel
    Assembly Version: 4.0.3.0
    Win32 Version: 4.700.19.51008
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.0.1/System.ComponentModel.dll
----------------------------------------
System.Collections.NonGeneric
    Assembly Version: 4.1.1.0
    Win32 Version: 4.700.19.51008
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.0.1/System.Collections.NonGeneric.dll
----------------------------------------
System.Memory
    Assembly Version: 4.2.0.0
    Win32 Version: 4.700.19.51008
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.0.1/System.Memory.dll
----------------------------------------
System.Buffers
    Assembly Version: 4.0.4.0
    Win32 Version: 4.700.19.51008
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.0.1/System.Buffers.dll
----------------------------------------
System.Resources.Extensions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.700.19.46214
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/3.0.1/System.Resources.Extensions.dll
----------------------------------------
netstandard
    Assembly Version: 2.1.0.0
    Win32 Version: 4.700.19.51008
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.0.1/netstandard.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.800.19.48001
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/3.0.1/System.Drawing.dll
----------------------------------------
System.ObjectModel
    Assembly Version: 4.1.1.0
    Win32 Version: 4.700.19.51008
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.0.1/System.ObjectModel.dll
----------------------------------------
System.Linq
    Assembly Version: 4.2.1.0
    Win32 Version: 4.700.19.51008
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.0.1/System.Linq.dll
----------------------------------------
System.Windows.Extensions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.700.19.46214
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/3.0.1/System.Windows.Extensions.dll
----------------------------------------
System.Reflection
    Assembly Version: 4.2.1.0
    Win32 Version: 4.700.19.51008
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.0.1/System.Reflection.dll
----------------------------------------
System.IO.FileSystem
    Assembly Version: 4.1.1.0
    Win32 Version: 4.700.19.51008
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.0.1/System.IO.FileSystem.dll
----------------------------------------
RenderWareFile
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/tools/HeroesPowerPlant_v0.8.9/RenderWareFile.dll
----------------------------------------
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.700.19.51008
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.0.1/mscorlib.dll
----------------------------------------
System.Text.RegularExpressions
    Assembly Version: 4.2.1.0
    Win32 Version: 4.700.19.51008
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.0.1/System.Text.RegularExpressions.dll
----------------------------------------
SharpDX.D3DCompiler
    Assembly Version: 4.2.0.0
    Win32 Version: 4.2.0
    CodeBase: file:///C:/tools/HeroesPowerPlant_v0.8.9/SharpDX.D3DCompiler.dll
----------------------------------------
System.Text.Encoding
    Assembly Version: 4.1.1.0
    Win32 Version: 4.700.19.51008
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.0.1/System.Text.Encoding.dll
----------------------------------------
System.IO
    Assembly Version: 4.2.1.0
    Win32 Version: 4.700.19.51008
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.0.1/System.IO.dll
----------------------------------------
System.Globalization
    Assembly Version: 4.1.1.0
    Win32 Version: 4.700.19.51008
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.0.1/System.Globalization.dll
----------------------------------------
System.Private.Uri
    Assembly Version: 4.0.5.0
    Win32 Version: 4.700.19.51008
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.0.1/System.Private.Uri.dll
----------------------------------------
GenericStageInjectionCommon
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/tools/HeroesPowerPlant_v0.8.9/GenericStageInjectionCommon.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 12.0.0.0
    Win32 Version: 12.0.3.23909
    CodeBase: file:///C:/tools/HeroesPowerPlant_v0.8.9/Newtonsoft.Json.dll
----------------------------------------
System.Runtime.Serialization.Formatters
    Assembly Version: 4.0.3.0
    Win32 Version: 4.700.19.51008
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.0.1/System.Runtime.Serialization.Formatters.dll
----------------------------------------
System.Linq.Expressions
    Assembly Version: 4.2.1.0
    Win32 Version: 4.700.19.51008
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.0.1/System.Linq.Expressions.dll
----------------------------------------
System.Runtime.Numerics
    Assembly Version: 4.1.1.0
    Win32 Version: 4.700.19.51008
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.0.1/System.Runtime.Numerics.dll
----------------------------------------
System.Runtime.Serialization.Primitives
    Assembly Version: 4.2.1.0
    Win32 Version: 4.700.19.51008
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.0.1/System.Runtime.Serialization.Primitives.dll
----------------------------------------
System.Data.Common
    Assembly Version: 4.2.1.0
    Win32 Version: 4.700.19.51008
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.0.1/System.Data.Common.dll
----------------------------------------
System.Xml.ReaderWriter
    Assembly Version: 4.2.1.0
    Win32 Version: 4.700.19.51008
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.0.1/System.Xml.ReaderWriter.dll
----------------------------------------
System.Private.Xml
    Assembly Version: 4.0.1.0
    Win32 Version: 4.700.19.51008
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.0.1/System.Private.Xml.dll
----------------------------------------
System.Reflection.Emit.ILGeneration
    Assembly Version: 4.1.0.0
    Win32 Version: 4.700.19.51008
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.0.1/System.Reflection.Emit.ILGeneration.dll
----------------------------------------
System.Reflection.Primitives
    Assembly Version: 4.1.1.0
    Win32 Version: 4.700.19.51008
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.0.1/System.Reflection.Primitives.dll
----------------------------------------
System.Reflection.Emit.Lightweight
    Assembly Version: 4.1.0.0
    Win32 Version: 4.700.19.51008
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.0.1/System.Reflection.Emit.Lightweight.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.700.19.47502
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.0.1/System.Private.CoreLib.dll
----------------------------------------
System.Net.Requests
    Assembly Version: 4.1.1.0
    Win32 Version: 4.700.19.51008
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.0.1/System.Net.Requests.dll
----------------------------------------
System.Net.Primitives
    Assembly Version: 4.1.1.0
    Win32 Version: 4.700.19.51008
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.0.1/System.Net.Primitives.dll
----------------------------------------
System.Net.WebClient
    Assembly Version: 4.0.1.0
    Win32 Version: 4.700.19.51008
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.0.1/System.Net.WebClient.dll
----------------------------------------
System.Security.Principal
    Assembly Version: 4.1.1.0
    Win32 Version: 4.700.19.51008
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.0.1/System.Security.Principal.dll
----------------------------------------
System.IO.Compression.ZipFile
    Assembly Version: 4.0.4.0
    Win32 Version: 4.700.19.51008
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.0.1/System.IO.Compression.ZipFile.dll
----------------------------------------
System.Diagnostics.Tracing
    Assembly Version: 4.2.1.0
    Win32 Version: 4.700.19.51008
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.0.1/System.Diagnostics.Tracing.dll
----------------------------------------
System.Net.WebHeaderCollection
    Assembly Version: 4.1.1.0
    Win32 Version: 4.700.19.51008
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.0.1/System.Net.WebHeaderCollection.dll
----------------------------------------
System.Net.Http
    Assembly Version: 4.2.1.0
    Win32 Version: 4.700.19.51008
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.0.1/System.Net.Http.dll
----------------------------------------
System.Threading.Tasks
    Assembly Version: 4.1.1.0
    Win32 Version: 4.700.19.51008
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.0.1/System.Threading.Tasks.dll
----------------------------------------
System.Security.Cryptography.X509Certificates
    Assembly Version: 4.2.1.0
    Win32 Version: 4.700.19.51008
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.0.1/System.Security.Cryptography.X509Certificates.dll
----------------------------------------
System.Net.ServicePoint
    Assembly Version: 4.0.1.0
    Win32 Version: 4.700.19.51008
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.0.1/System.Net.ServicePoint.dll
----------------------------------------
System.Security.Cryptography.Primitives
    Assembly Version: 4.1.1.0
    Win32 Version: 4.700.19.51008
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.0.1/System.Security.Cryptography.Primitives.dll
----------------------------------------
System.Net.Security
    Assembly Version: 4.1.1.0
    Win32 Version: 4.700.19.51008
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.0.1/System.Net.Security.dll
----------------------------------------
System.Diagnostics.DiagnosticSource
    Assembly Version: 4.0.4.0
    Win32 Version: 4.700.19.51008
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.0.1/System.Diagnostics.DiagnosticSource.dll
----------------------------------------
System.Threading.Timer
    Assembly Version: 4.1.1.0
    Win32 Version: 4.700.19.51008
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.0.1/System.Threading.Timer.dll
----------------------------------------
System.Net.Sockets
    Assembly Version: 4.2.1.0
    Win32 Version: 4.700.19.51008
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.0.1/System.Net.Sockets.dll
----------------------------------------
System.Threading.Overlapped
    Assembly Version: 4.1.1.0
    Win32 Version: 4.700.19.51008
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.0.1/System.Threading.Overlapped.dll
----------------------------------------
System.Net.NameResolution
    Assembly Version: 4.1.1.0
    Win32 Version: 4.700.19.51008
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.0.1/System.Net.NameResolution.dll
----------------------------------------
System.Security.Principal.Windows
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.19.51008
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.0.1/System.Security.Principal.Windows.dll
----------------------------------------
System.Security.Claims
    Assembly Version: 4.1.1.0
    Win32 Version: 4.700.19.51008
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.0.1/System.Security.Claims.dll
----------------------------------------
System.Threading.ThreadPool
    Assembly Version: 4.1.1.0
    Win32 Version: 4.700.19.51008
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.0.1/System.Threading.ThreadPool.dll
----------------------------------------
System.Security.Cryptography.Encoding
    Assembly Version: 4.1.1.0
    Win32 Version: 4.700.19.51008
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.0.1/System.Security.Cryptography.Encoding.dll
----------------------------------------
System.IO.Compression
    Assembly Version: 4.2.1.0
    Win32 Version: 4.700.19.51008
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.0.1/System.IO.Compression.dll
----------------------------------------
SharpDX.Desktop
    Assembly Version: 4.2.0.0
    Win32 Version: 4.2.0
    CodeBase: file:///C:/tools/HeroesPowerPlant_v0.8.9/SharpDX.Desktop.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.700.19.51008
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.0.1/System.dll
----------------------------------------
System.Numerics.Vectors
    Assembly Version: 4.1.5.0
    Win32 Version: 4.700.19.51008
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.0.1/System.Numerics.Vectors.dll
----------------------------------------
System.Diagnostics.StackTrace
    Assembly Version: 4.1.1.0
    Win32 Version: 4.700.19.51008
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.0.1/System.Diagnostics.StackTrace.dll
----------------------------------------
System.Reflection.Metadata
    Assembly Version: 1.4.4.0
    Win32 Version: 4.700.19.51008
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.0.1/System.Reflection.Metadata.dll
----------------------------------------
System.Collections.Immutable
    Assembly Version: 1.2.4.0
    Win32 Version: 4.700.19.51008
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.0.1/System.Collections.Immutable.dll
----------------------------------------

************** JIT Debugging **************
```

**Comment by dreamsyntax** [comment]
@Muzzarino I know this is very old but is this still an issue?
Would need to check if this is present in v0.10.0

**Comment by dreamsyntax** [comment]
Confirmed this issue is still present as of 2022.07.19 HPP for Config Editor -> EXE Data Extractor

LayoutEditor GetPosition for P1/P2/P3 works, Rotation does not (might be implemented)

**Comment by dreamsyntax** [comment]
This has been fixed and will be in the next release.
